name: CVM_vis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - numpy=1.24.4
  - pandas=2.0.3
  - trimesh=4.2.0
  - vtk=9.2.2
  - xarray=2022.9.0
  - scipy=1.9.2
  - scikit-learn=1.1.2
  - tqdm=4.66.5
  - pymeshlab=2023.12.post1
  - pyproj=3.4.0
  - pip=24.2
